### ISSUE TITLE
Merge to latest ycm/ycmd?

### ISSUE THREAD

**Issue by RedBeard0531** [oblitum/YouCompleteMe#21]
Any plans to merge or rebase your patch to the latest ycm and ycmd? I've had to switch back to upstream to use the latest clang since the version you link against is missing some important features. But now I sorely miss the argument hints!

I thought I should check if you were planning on updating any time soon before trying to do it myself.

**Comment by oblitum** [comment]
There's no estimative, I'm really not expecting to work on merge anytime soon, the last merge with upstream I did was the last one because the upstream commit following it added breaking changes regarding async completion that make merge not straightforward. Currently [I just use `--system-libclang`](https://github.com/oblitum/dotfiles/blob/0e9c3266a9ab75eff147ce695872803a57e45489/.vimrc#L49) to avoid your issue. Another fact that I'm not interested in working on a merge is because I have many grips with YCM, in fact I dislike it and use it solely due to inertia, I hope to work on my own completion plugin one day and leave all YCM issues aside for good.
