### ISSUE TITLE
Can't get it working on Yosemite

### ISSUE THREAD

**Issue by jsholmes** [oblitum/YouCompleteMe#8]
I think this is mostly a path issue at this point on Yosemite, but I can't seem to get this working.

My llvm 3.7 is installed to /usr/local/opt/llvm/bin/clang

My system clang is in /usr/bin/clang

install.sh is picking up the yosemite default 3.5 clang:
❯ ./install.sh --system-libclang --clang-completer
-- The C compiler identification is AppleClang 6.0.0.6000056

my PATH picks up the correct clang first:
which -a clang
/usr/local/opt/llvm/bin/clang
/usr/bin/clang

❯ cat /etc/paths
/usr/local/opt/llvm/bin
/usr/local/opt/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

Not quite sure what to try or how builds on mac figure out which clang to use.

I even tried renaming /usr/bin/clang to /usr/bin/clang.old, but it was undeterred and kept using clang 6.0.0.6.

I guess it's actually getting it from:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

But how do I tell it to look somewhere else?

**Comment by oblitum** [comment]
Try to run `./install.sh` with preceding, e.g., `CPATH=/usr/local/opt/llvm/include`. `CPATH` is the environment variable you normally use for adding aditional default header paths. Just having an additional binary directory in `PATH` is not enough for using the correct clang to build.

**Comment by oblitum** [comment]
@jsholmes by the way... My compilation also shows to be using the system's clang `AppleClang 6.0.0.6000056`, but the build works!

I didn't care about the messages since it's always working for me, I guess it uses the correct headers the way I have explained, but doesn't pick the custom clang for compiling the project.

For the build to pick the custom clang for compiling the project you may set addtional normally used flags. I've just tried setting:

```
export CC=/opt/local/bin/clang
export CXX=/opt/local/bin/clang++
```

and `./install.sh` picked this clang for compiling the project. But in truth, this shouldn't matter if you set the correct clang headers.

**Comment by oblitum** [comment]
@jsholmes Hi, I just verified that just by setting `CC` to `/opt/local/bin/clang` the correct headers are picked, no `CPATH` setting needed. Can you please verify whether this works for you too? Don't use `CPATH` (`unset CPATH`), nor `CXX`, clean them all (check with `echo $CPATH`). Set `CC` and try to build. I'd like to put simpler instruction on README.

**Comment by oblitum** [comment]
@jsholmes my bad, `CPATH` is also required to be set, just verified.

For me, this builds with Apple's Clang:

```
CPATH=/opt/local/include ./install.sh --clang-completer --system-libclang
```
and this with my own:

```
CPATH=/opt/local/include CC=/opt/local/bin/clang ./install.sh --clang-completer --system-libclang
```

**Comment by oblitum** [comment]
@jsholmes did you solve your problem?

**Comment by jsholmes** [comment]
I tried again today.  The build instructions work, but it's still using the libclang.dylib from:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib

Rather than the one from:
/usr/local/Cellar/llvm/HEAD/lib/libclang.dylib

Is there some new environment variable I must give it to get it to pick this up?

**Comment by oblitum** [comment]
@jsholmes you may add `/opt/local/lib` to `DYLD_LIBRARY_PATH`, it will sure load, although it should be loading already since the build is expected to make a local copy of libclang.dylib...

**Comment by jsholmes** [comment]
Well, I just made the local copy:
cp /usr/local/Cellar/llvm/HEAD/lib/libclang.dylib third_party/ycmd/libclang.dylib

It's now working as intended!  Super great.

That said, it doesn't show me parameters in the completion dropdown for functions (like your previous fork did), but only the return value.  Is there an option to turn this on or is it totally disabled now in favor of the new stuff?  It would also be awesome to show doxygen comments using http://clang.llvm.org/docs/UsersManual.html#comment-parsing-options.  Is that available through libclang?

**Comment by oblitum** [comment]
> That said, it doesn't show me parameters in the completion dropdown for functions (like your previous fork did), but only the return value.  Is there an option to turn this on or is it totally disabled now in favor of the new stuff?

Currently there isn't an option to enable it back, I removed this in this fork because it was quite common to get long prototypes and the popup getting  less useful than intended, without one able to see the return type for example. Now you just get a single name, not a long list of overloads in the popup, if you want to see the overloads for a given function just enable the preview window and they will show there, it'll also highlight the current argument.
This relates to issue #1287 and I've referred it in the source code [here](https://github.com/oblitum/ycmd/blob/master/cpp/ycm/ClangCompleter/CompletionData.cpp#L157-L159), it's just that line that turns on this behavior.
I'm currently thinking of providing alternative solutions, but the options that clutter the popup are not of my taste really.

> It would also be awesome to show doxygen comments using http://clang.llvm.org/docs/UsersManual.html#comment-parsing-options.  Is that available through libclang?

It's already enabled, but I dunno why sometimes clang doesn't grab them. I've tested it here for example:

![doxygen in preview](http://i.imgur.com/NVniXq6.gif)

It should be a bug in libclang I guess, beside trivial samples it never gets the briefs, also it seems libclang just support briefs. My clang modifications currently try to attach doxygen for each param but it just does nothing, so you get doxygen only for the brief when selecting a function, and when it works.

I guess this doxygen support needs to be improved a lot.

**Comment by oblitum** [comment]
notice the old branch simulating clang_complete is still there if you liked it more.

**Comment by jsholmes** [comment]
Ah ok.  I didn't have preview in my completion options because I find it a bit slow and useless, but this actually makes it useful, so I'll give ye olde preview window another try.

**Comment by oblitum** [comment]
@jsholmes I'm also in the same boat, I just enable them rarely when I feel the need. I'm think of creating a mapping for toggling it when I find it necessary.
